// Package usecase contains application-layer business logic.
package usecase

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"github.com/google/uuid"

	"kawan-threads/internal/domain/entity"
	"kawan-threads/internal/domain/port"
	"kawan-threads/internal/domain/repository"
	applogger "kawan-threads/internal/logger"
)

// ContentUseCase orchestrates content generation and editing.
type ContentUseCase struct {
	ContentRepo  repository.ContentRepository
	VersionRepo  repository.ContentVersionRepository
	HistoryRepo  repository.HistoryRepository
	AIProvider   port.AIProvider
	Logger       *slog.Logger
	AutoApproval bool
}

// EditContentRequest holds the fields an admin can change.
type EditContentRequest struct {
	Hook                 string `json:"hook"`
	Body                 string `json:"body"`
	CTA                  string `json:"cta"`
	ConversationQuestion string `json:"conversation_question"`
	HookType             string `json:"hook_type"`
	SelectedHookVariant  string `json:"selected_hook_variant"`
	Reason               string `json:"reason"`
}

// GenerateContent calls the AI, creates a DRAFT Content, and persists it.
// Content ALWAYS starts as DRAFT — never queued or published directly.
func (uc *ContentUseCase) GenerateContent(ctx context.Context, req port.GenerateContentRequest) (*entity.Content, error) {
	applogger.LogEvent(uc.Logger, applogger.EventGeminiGenerationStarted,
		"pillar", string(req.Pillar),
		"topic", req.Topic,
		"format", string(req.Format),
	)

	generated, err := uc.AIProvider.GenerateContent(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("AI generation failed: %w", err)
	}

	now := time.Now().UTC()
	variants := make([]entity.HookVariant, 0, len(generated.HookVariants))
	for _, v := range generated.HookVariants {
		variants = append(variants, entity.HookVariant{Hook: v.Hook, HookType: v.HookType})
	}

	content := &entity.Content{
		ID:                   uuid.New().String(),
		Pillar:               req.Pillar,
		Topic:                generated.Topic,
		Audience:             req.Audience,
		Tone:                 req.Tone,
		Format:               req.Format,
		CTA:                  generated.CTA,
		Hook:                 generated.Hook,
		HookVariants:         variants,
		Body:                 generated.Body,
		ConversationQuestion: generated.ConversationQuestion,
		HookType:             generated.HookType,
		ContentType:          generated.ContentType,
		Quality:              generated.Quality,
		// CRITICAL: Status is always DRAFT after generation
		Status:        entity.StatusDraft,
		Source:        "GEMINI",
		Version:       1,
		PromptVersion: generated.PromptVersion,
		Model:         generated.Model,
		CreatedAt:     now,
		UpdatedAt:     now,
	}

	if err := uc.ContentRepo.Save(ctx, content); err != nil {
		return nil, fmt.Errorf("save content: %w", err)
	}

	// Save initial version snapshot.
	version := &entity.ContentVersion{
		ID:                   uuid.New().String(),
		ContentID:            content.ID,
		Version:              1,
		Hook:                 content.Hook,
		Body:                 content.Body,
		CTA:                  content.CTA,
		ConversationQuestion: content.ConversationQuestion,
		EditedBy:             "GEMINI",
		EditedAt:             now,
		Reason:               "initial AI generation",
	}
	if err := uc.VersionRepo.Save(ctx, version); err != nil {
		uc.Logger.Warn("failed to save initial version", "content_id", content.ID, "error", err)
	}

	// Save history entry.
	_ = uc.saveHistory(ctx, content.ID, "", entity.StatusDraft, "system", "content generated by AI")

	applogger.LogEvent(uc.Logger, applogger.EventContentGenerated,
		"content_id", content.ID,
		"pillar", string(content.Pillar),
		"score", content.Quality.Relevance,
		"model", content.Model,
	)

	return content, nil
}

// GetContent retrieves a content item with its versions and history.
func (uc *ContentUseCase) GetContent(ctx context.Context, id string) (*entity.Content, error) {
	c, err := uc.ContentRepo.FindByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("find content: %w", err)
	}
	if c == nil {
		return nil, fmt.Errorf("content %s not found", id)
	}
	return c, nil
}

// UpdateContent applies admin edits to a content item, bumps the version, and
// saves a ContentVersion snapshot.
func (uc *ContentUseCase) UpdateContent(ctx context.Context, id string, req EditContentRequest) (*entity.Content, error) {
	c, err := uc.ContentRepo.FindByID(ctx, id)
	if err != nil || c == nil {
		return nil, fmt.Errorf("content %s not found", id)
	}

	// Apply changes.
	if req.Hook != "" {
		c.Hook = req.Hook
	}
	if req.Body != "" {
		c.Body = req.Body
	}
	if req.CTA != "" {
		c.CTA = req.CTA
	}
	if req.ConversationQuestion != "" {
		c.ConversationQuestion = req.ConversationQuestion
	}
	if req.HookType != "" {
		c.HookType = entity.HookType(req.HookType)
	}

	c.Version++
	c.UpdatedAt = time.Now().UTC()

	if err := uc.ContentRepo.Update(ctx, c); err != nil {
		return nil, fmt.Errorf("update content: %w", err)
	}

	// Save version snapshot.
	ver := &entity.ContentVersion{
		ID:                   uuid.New().String(),
		ContentID:            c.ID,
		Version:              c.Version,
		Hook:                 c.Hook,
		Body:                 c.Body,
		CTA:                  c.CTA,
		ConversationQuestion: c.ConversationQuestion,
		EditedBy:             "admin",
		EditedAt:             c.UpdatedAt,
		Reason:               req.Reason,
	}
	if err := uc.VersionRepo.Save(ctx, ver); err != nil {
		uc.Logger.Warn("failed to save version", "content_id", c.ID, "error", err)
	}

	_ = uc.saveHistory(ctx, c.ID, c.Status, c.Status, "admin", fmt.Sprintf("edited: %s", req.Reason))
	return c, nil
}

// RegenerateContent calls the AI again for the same prompt params and
// replaces the content body, keeping it as DRAFT.
func (uc *ContentUseCase) RegenerateContent(ctx context.Context, id string, req port.GenerateContentRequest) (*entity.Content, error) {
	c, err := uc.ContentRepo.FindByID(ctx, id)
	if err != nil || c == nil {
		return nil, fmt.Errorf("content %s not found", id)
	}

	applogger.LogEvent(uc.Logger, applogger.EventGeminiGenerationStarted,
		"content_id", id,
		"pillar", string(req.Pillar),
		"action", "regenerate",
	)

	generated, err := uc.AIProvider.GenerateContent(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("AI regeneration failed: %w", err)
	}

	now := time.Now().UTC()
	c.Hook = generated.Hook
	variants := make([]entity.HookVariant, 0, len(generated.HookVariants))
	for _, v := range generated.HookVariants {
		variants = append(variants, entity.HookVariant{Hook: v.Hook, HookType: v.HookType})
	}
	c.HookVariants = variants
	c.Body = generated.Body
	c.CTA = generated.CTA
	c.ConversationQuestion = generated.ConversationQuestion
	c.HookType = generated.HookType
	c.Quality = generated.Quality
	c.Model = generated.Model
	c.PromptVersion = generated.PromptVersion
	c.Version++
	c.UpdatedAt = now
	// Reset to DRAFT after regeneration
	c.Status = entity.StatusDraft

	if err := uc.ContentRepo.Update(ctx, c); err != nil {
		return nil, fmt.Errorf("update content: %w", err)
	}

	ver := &entity.ContentVersion{
		ID:                   uuid.New().String(),
		ContentID:            c.ID,
		Version:              c.Version,
		Hook:                 c.Hook,
		Body:                 c.Body,
		CTA:                  c.CTA,
		ConversationQuestion: c.ConversationQuestion,
		EditedBy:             "GEMINI",
		EditedAt:             now,
		Reason:               "regenerated by AI",
	}
	if err := uc.VersionRepo.Save(ctx, ver); err != nil {
		uc.Logger.Warn("failed to save regen version", "content_id", c.ID, "error", err)
	}

	_ = uc.saveHistory(ctx, c.ID, c.Status, entity.StatusDraft, "system", "content regenerated by AI")
	return c, nil
}

// saveHistory persists a History entry, logging on failure.
func (uc *ContentUseCase) saveHistory(ctx context.Context, contentID string, from, to entity.ContentStatus, actor, note string) error {
	h := &entity.History{
		ID:        uuid.New().String(),
		ContentID: contentID,
		Action:    fmt.Sprintf("%s→%s", from, to),
		OldStatus: from,
		NewStatus: to,
		Actor:     actor,
		Note:      note,
		CreatedAt: time.Now().UTC(),
	}
	if err := uc.HistoryRepo.Save(ctx, h); err != nil {
		uc.Logger.Error("save history failed", "content_id", contentID, "error", err)
		return err
	}
	return nil
}
